wheel_of_life = {
    "Freizeit": {
        "🎮 Konnte zoocken": 1,
        "🎬 Konnte Filme schauen": 1,
        "📺 Konnte Serien schauen": 1,
        "🎵 Konnte Musik hören": 1,
        "🌳 Konnte Zeit in der Natur verbringen": 2,
        "📱 Nur am Handy verbracht": -2,
        "😑 Langeweile gehabt": -1,
    },
    "Arbeit & Karriere": {
        "💼 Konnte arbeiten": 2,
        "📚 Konnte lernen": 2,
        "🎨 Konnte kreativ sein": 2,
        "✅ Konnte Projekte abschließen": 2,
        "🧘 Konnte entspannen": 1,
        "⏳ Arbeit aufgeschoben": -2,
        "❌ Fehler gemacht": -1,
    },
    "Persönliche Wachstum": {
        "📖 Konnte lesen": 2,
        "📚 Konnte lernen": 2,
        "✍️ Konnte schreiben": 2,
        "🎨 Konnte kreativ sein": 2,
        "🤔 Konnte reflektieren": 2,
        "⏰ Keine Zeit für Entwicklung": -2,
        "😕 Unzufrieden mit Fortschritt": -1,
    },
    "Wohlbefinden": {
        "🧘 Konnte entspannen": 2,
        "🧘‍♂️ Konnte meditieren": 2,
        "😴 Konnte ausreichend schlafen": 2,
        "🎨 Konnte kreativ sein": 2,
        "📖 Konnte lesen": 2,
        "😰 Gestresst gefühlt": -2,
        "🌙 Zu wenig Schlaf": -1,
    },
    "Gesundheit & Fitness": {
        "🏃‍♂️ Konnte joggen": 2,
        "🧘‍♀️ Konnte Yoga machen": 2,
        "🧘 Konnte meditieren": 2,
        "🥗 Konnte gesund essen": 2,
        "📋 Essen getrackt": 2,
        "🍔 Fast Food gegessen": -2,
        "🛋️ Kein Sport gemacht": -1,
    },
    "Komfortzone": {
        "🆕 Konnte neue Dinge ausprobieren": 2,
        "💪 Konnte mich Herausforderungen stellen": 2,
        "😨 Konnte Ängste überwinden": 2,
        "🗣️ Konnte Feedback annehmen": 2,
        "🔄 Konnte aus Fehlern lernen": 2,
        "🙈 Neues vermieden": -2,
        "😟 Aus Angst zurückgezogen": -1,
    },
    "Werte gelebt": {
        "🤝 Ehrlich gewesen": 2,
        "🤲 Hilfsbereit gewesen": 2,
        "🧑‍💼 Verantwortung übernommen": 2,
        "🙏 Respektvoll gehandelt": 2,
        "🌱 Nachhaltig gehandelt": 2,
        "🚫 Werte ignoriert": -2,
        "🙃 Unaufrichtig gewesen": -1,
    },
    "Beziehung & Liebe": {
        "💋 Guten Morgen Kuss gegeben": 2,
        "💋 Guten Abend Kuss gegeben": 2,
        "❤️ Zeit mit Partner verbracht": 2,
        "💬 Offen kommuniziert": 2,
        "😄 Spaß gehabt": 2,
        "💔 Streit gehabt": -2,
        "🙄 Wenig Aufmerksamkeit geschenkt": -1,
    },
    "Sozialleben": {
        "👫 Konnte Freunde treffen": 2,
        "👨‍👩‍👧‍👦 Konnte Familie treffen": 2,
        "🧑‍🤝‍🧑 Konnte neue Leute kennenlernen": 2,
        "🗣️ Gute Gespräche geführt": 2,
        "🤗 Jemandem geholfen": 2,
        "😡 Streit mit Freunden": -2,
        "😔 Einsam gefühlt": -1,
    },
    "Finanzen": {
        "🤑 Kein Geld ausgegeben": 5,
        "💳 Konnte Rechnungen bezahlen": 2,
        "💰 Konnte Geld sparen": 2,
        "📈 Konnte Geld investieren": 2,
        "💵 Konnte Geld verdienen": 2,
        "📊 Ausgaben getrackt": 2,
        "💸 Geld verschwendet": -3,
    },
}
